# _*_ coding:utf-8 _*_
__author__ = 'caimiao'
__date__ = '15-5-5'

DEBUG_MODE = False

# 主数据库配置
_MYSQL_MASTER_HOST_DEBUG = '127.0.0.1:3306'
_MYSQL_MASTER_DB_DEBUG = 'prehistory'
_MYSQL_MASTER_USER_DEBUG = 'arch'
_MYSQL_MASTER_PWD_DEBUG = '123456'

_MYSQL_MASTER_HOST_NORMAL = '127.0.0.1:3306'
_MYSQL_MASTER_DB_NORMAL = 'prehistory'
_MYSQL_MASTER_USER_NORMAL = 'arch'
_MYSQL_MASTER_PWD_NORMAL = '123456'

MYSQL_MASTER_HOST = _MYSQL_MASTER_HOST_DEBUG if DEBUG_MODE else _MYSQL_MASTER_HOST_NORMAL
MYSQL_MASTER_DB = _MYSQL_MASTER_DB_DEBUG if DEBUG_MODE else _MYSQL_MASTER_DB_NORMAL
MYSQL_MASTER_USER = _MYSQL_MASTER_USER_DEBUG if DEBUG_MODE else _MYSQL_MASTER_USER_NORMAL
MYSQL_MASTER_PWD = _MYSQL_MASTER_PWD_DEBUG if DEBUG_MODE else _MYSQL_MASTER_PWD_NORMAL